name: Shell Commands

on: [push]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: multiline script
        run: |
          echo ${{ github.event.commits[0].message}} 
